run:
  timeout: 3m
  build-tags:
    - apparmor
    - containers_image_openpgp
    - e2e_test
    - fakeroot_engine
    - seccomp
    - selinux
    - singularity_engine
    - sylog
  skip-files:
    - "internal/pkg/util/user/cgo_lookup_unix.go"

linters:
  disable-all: true
  enable-all: false
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - dupword
    - exportloopref
    - forcetypeassert
    - gofumpt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - maintidx
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - reassign
    - revive
    - staticcheck
    - typecheck
    - unused

linters-settings:
  misspell:
    locale: US

issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    # EXC0004 excluded due to spurious "should have signature XYZ" errors on
    # MarshalJSON methods. See
    # https://golangci-lint.run/usage/false-positives/#exc0004 for more
    # information.
    - EXC0004
  exclude-rules:
    - linters:
        - gosec
      # G107 disallows making http calls to a URL stored in a variable
      # G204 disallows exec.Command() with a command/args stored in variables
      # G306 disallows creation of files with permissions greater than 0600
      text: "^(G107|G204|G306):"

