# Allow repeated headers (changelog sections)
MD024: false
# Allow hard tabs (go snippets in e2e)
MD010: false
# Line-length
MD013:
  # Disable line-length check inside code blocks
  code_blocks: false
